### ISSUE TITLE
Mobile Server Side Account Creation

### ISSUE THREAD

**Issue by nh758** [appdevdesigns/appbuilder_platform_mobile#3]

**Comment by joshAppDev** [comment]
When we send out the QR codes / magic links to users, they each receive a `pre-token`. Using this, they can register the `auth token` for their device. (This happens behind the scenes. No extra steps needed by the user.)

Some config choices:

### Expiration of pre-tokens
How long after the pre-token is sent out before it expires? Current default is **7 days**.

### Re-usability of pre-tokens
After a pre-token is used (i.e. when the user scans their QR code), the pre-token is expended. If the user needs to activate another device for their account, they will need a new pre-token (magic link QR code). This protects against a hacker finding their QR code and secretly registering another device to their account.  However, if users actually need the ability to activate multiple devices with the same QR code, it is possible to allow that. Current default is **not allowed**.

### Max limit of mobile devices per user
When a new device is registered, the server can delete old auth tokens associated with the user. This helps to prevent the database from accumulating lots of old auth tokens that will never be used again. It can also serve as a warning sign of an unauthorized registration if a user suddenly finds that their auth token is no longer accepted. Not too sure about this one. The current default is **3 devices** per user. If exceeded, the server will delete the oldest auth token first.

**Comment by joshAppDev** [comment]
## Mobile Accounts

Mobile accounts are stored in the `appbuilder_relay_user` table. Each entry has
a counterpart on the MCC relay server's `mcc_relay_user` table. Neither of these
strictly needs to be administered from within AppBuilder. This presents an 
opportunity to simplify the user experience.

Currently the way to administer mobile accounts is to load AppBuilder, then
go to the Settings tab. Under the new mobile account system, QR code tokens
are single-use only. So there needs to be a way to generate new QR code tokens
on demand. Also, the contents of the QR codes will be totally different. The
mobile account admin will need to be revamped.

We can create standalone pages on the AppBuilder site, not part of the usual 
Webix menu system, but that can be loaded directly through a bookmarked URL. 
These pages can load quickly since they only have one purpose. So for example, 
if a user simply wants to scan their QR code from the site, they go to the URL 
and the QR code can be the first thing they see after authenticating.

As a bonus, these types of pages are easier for me to make.


## Mobile Account Management Pages

### Account Details

```
https://DOMAIN-NAME/mobile/account
```

A webpage for a user to view their mobile account info. From here, they
can generate a new registration QR code and display it on the screen. They can
also optionally send it to their secure email account.

There will be a function to display a list of all the devices currently 
linked to their account. They can remove items from this list if anything looks
suspicious or if they know that device is no longer in use.

The page will send the relevant changes to the MCC relay server.

### Account Admin

```
https://DOMAIN-NAME/mobile/admin
```

A webpage for admins to manage mobile accounts of users on the site.

#### View 1: Site users who don't have mobile accounts

Admins can select users from the list to activate their mobile accounts.
The encryption keys and registration tokens will be generated. The QR codes will
be sent to the users' secure email.

#### View 2: Mobile users list

Admins can select a user to drill down into the details. This will bring them 
to the `/mobile/account` page of that user, as described above.


## Focus

Wei has suggested that I should focus more on stability and performance first
before adding new features. That makes sense to me, given the current user 
experience of the NS. I can leave some features until later, like the function
displaying a user's linked devices.
